import * as THREE from 'https://esm.sh/three@0.180.0';
import { OrbitControls } from 'https://esm.sh/three@0.180.0/examples/jsm/controls/OrbitControls.js';

export default {
  render({el}) {
    el.innerHTML = `<style>
    .cnc{background:#10181e;color:#ecf2f3;font:14px system-ui,sans-serif;padding:26px;border-radius:16px;max-width:1500px;margin:auto;box-sizing:border-box}.cnc *{box-sizing:border-box}.cnc h1{font-size:30px;letter-spacing:-1px;margin:7px 0}.cnc p{line-height:1.5;color:#abbac3}.cnc .eyebrow{font-size:11px;color:#67d8b5;letter-spacing:2px}.cnc .top{display:flex;justify-content:space-between;gap:24px}.cnc .pill{color:#cad6dd;background:#223039;border:1px solid #384952;border-radius:20px;padding:7px 12px;font-size:11px;white-space:nowrap;height:fit-content}.cnc .rail{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:24px 0 16px}.cnc button{cursor:pointer;background:#223039;color:#cbd8df;border:1px solid #354750;border-radius:8px;padding:11px;font:inherit}.cnc .rail button{font-size:12px;text-align:left}.cnc button.active{background:#123d35;border-color:#62d8b3;color:#90f4d0}.cnc .main{display:grid;grid-template-columns:minmax(0,2fr) minmax(285px,1fr);gap:16px}.cnc .view{height:425px;position:relative;background:#18232a;border-radius:10px;overflow:hidden}.cnc canvas{display:block;width:100%;height:100%}.cnc .overlay{position:absolute;left:16px;top:16px;pointer-events:none;color:#b4c7d3;font:11px ui-monospace,monospace}.cnc .axis{position:absolute;right:16px;bottom:14px;color:#85e2c1;font:12px ui-monospace,monospace}.cnc .panel{background:#1a262e;padding:20px;border-radius:10px}.cnc .panel h2{font-size:21px;margin:7px 0 13px;line-height:1.2}.cnc .item{border-top:1px solid #33434d;padding:11px 0;color:#b8c8d1;font-size:13px}.cnc .label{font-size:10px;letter-spacing:1.3px;color:#81959f;text-transform:uppercase;margin:18px 0 6px}.cnc .callout{border-left:3px solid #69d7b7;background:#142f2b;padding:12px;line-height:1.5;color:#bce7db;font-size:13px}.cnc .controls{display:flex;align-items:center;gap:12px;padding:14px 0}.cnc .controls input{flex:1;accent-color:#6eddb8;min-width:50px}.cnc .graphs{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;margin-top:12px}.cnc .graph{padding:18px;border:1px solid #30414a;border-radius:10px;min-width:0}.cnc .graph h3{font-size:13px;margin:0 0 12px}.cnc .graph small{display:block;color:#8fa3ad;font-size:11px;line-height:1.5}.cnc svg{max-width:100%;height:110px;display:block}.cnc .legend{display:flex;gap:12px;color:#9eafb8;font-size:11px}.cnc code{color:#9ae8cb;font-size:11px;white-space:pre-wrap}.cnc .foot{font-size:11px;color:#8c9fa9;border-top:1px solid #30414a;padding-top:14px;margin-top:18px}.cnc .tools{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.cnc .tool{font-size:11px;padding:6px 9px;background:#24343d;border-radius:5px}.cnc .warn{color:#ff9d91}.cnc .available{display:flex;gap:8px;align-items:center;font-size:12px;color:#b8c8d1} @media(max-width:850px){.cnc .main,.cnc .graphs{grid-template-columns:1fr}.cnc .rail{grid-template-columns:repeat(3,1fr)}}
    </style>
    <div class="cnc"><div class="top"><div><div class="eyebrow">SILTA / CNC LEARNING LOOP</div><h1>A recipe this shop can make.</h1><p>Plan. Simulate. Turn a failure into a reusable check.</p></div><div class="pill">INTERACTIVE STORYBOARD · NOT A LIVE AGENT</div></div>
    <div class="tools"><span class="tool">3 axes · fixed spindle orientation</span><span class="tool">100 × 70 × 16 mm plate</span><span class="tool">T1 Ø4</span><span class="tool">T2 Ø6 / wide holder</span><span class="tool">T3 Ø6 / slim holder</span><span class="tool">T4 Ø8</span></div>
    <div class="rail"></div><div class="main"><div><div class="view"><div class="overlay">ILLUSTRATIVE MOTION REPLAY<br>Drag to orbit · scroll to zoom</div><div class="axis"></div></div><div class="controls"><button class="play">Play machine</button><input class="scrub" aria-label="Replay progress" type="range" min="0" max="1000" value="0"><span class="clock">0.0 s</span><button class="reset">Reset</button></div><label class="available"><input class="slim" type="checkbox" checked> T3 slim-holder assembly is available in this shop</label></div><div class="panel"></div></div>
    <div class="graphs"><div class="graph"><h3>Machine time · illustrative estimate</h3><div class="timechart"></div><small>Computed from these example motion sequences. 180 mm/min drilling, 3,000 mm/min rapid, 8 s/tool change. Acceleration omitted.</small></div><div class="graph"><h3>Learning efficiency · measurement plan</h3><svg viewBox="0 0 300 110"><path d="M28 10V85H290" fill="none" stroke="#4b636f"/><path d="M28 30H290M28 55H290" fill="none" stroke="#293e48" stroke-dasharray="3 5"/><text x="155" y="49" text-anchor="middle" fill="#90a6b2" font-size="12">Awaiting real benchmark runs</text><text x="155" y="105" text-anchor="middle" fill="#71918f" font-size="11">base checks → learned check versions</text></svg><small>Full simulations per verified job + solve rate. Include rejected-candidate audits and learning overhead.</small></div><div class="graph"><h3>Recipe cost · illustrative estimate</h3><div class="costchart"></div><small>Assumed $90/machine-hour + $15 setup / lot of 10. Material and tooling excluded. Planning compute tracked separately.</small></div></div>
    <div class="foot">This notebook proves the proposed presentation layout. Motion, costs and failure are illustrative. No model calls, generated-check learning, STEP verification or material-removal solver is attached. The finished app will replay the exact events and stock states produced by its verifier.</div></div>`;
    const $=s=>el.querySelector(s);
    const stages=[
      ['01 / Job','Part + shop','A dimensioned part, a machine and a finite tool library.','Input','STEP or confirmed drawing dimensions','Output','Typed job + immutable shop configuration','Stock already matches the outside envelope. We only need to drill the supported holes.'],
      ['02 / Plan','Propose the recipe','Assign existing tools and order the operations.','Input','Hole features + tool/fixture constraints','Output','Setup, tool IDs and compiled motion sequence','The recipe is separate from STEP geometry. Every tool and setup must exist in this shop.'],
      ['03 / Simulate','The holder hits the clamp','The drill can reach, but the wide holder cannot clear the fixture.','Input','Candidate with T2 short/wide holder','Output','Failure event + colliding bodies + tool pose','The finished verifier must calculate this failure. Here it is an illustrative, explicitly constructed scene.'],
      ['04 / Learn','Turn failure into a check','Generate a cheap holder-footprint and Z-overlap check.','Input','Labeled simulator failures and valid neighbors','Output','Candidate pure-function check + applicability','Show code changes, test evidence and false rejections. Only promote useful checks; the simulator stays fixed.'],
      ['05 / Transfer','Screen the next job earlier','Try a new hole location. Apply the learned rule before expensive simulation.','Input','New part + same shop + validated check version','Output','Reject T2 candidate; consider available alternatives','Transfer must be measured on unseen cases. A check passing does not replace final verification.'],
      ['06 / Result','Machine the final recipe','Use the slim holder and group operations by tool.','Input','Best fully verified recipe','Output','Completed-part replay + setup sheet + plan + STEP','Optimize only valid plans. Report estimated machine time and cost separately from planning compute.']
    ];
    let stage=0, playing=false, elapsed=0, queue=[], total=1, lastTs=0, frameId, oldDone=-1;
    const holes=[{x:-30,y:-20,d:4},{x:0,y:-20,d:6},{x:30,y:-20,d:8},{x:-30,y:20,d:4},{x:30,y:20,d:6},{x:0,y:20,d:8}];
    const route0=[0,1,2,3,4,5], route1=[0,3,1,4,2,5];
    function compile(order,wide=false,failure=false){let out=[],p=[0,0,60],t=0,prev=0; const add=(end,duration,kind,tool,hole=null)=>{out.push({from:[...p],to:[...end],start:t,end:t+duration,kind,tool,hole});t+=duration;p=[...end];};for(const i of order){const h=holes[i],tool=h.d===6?(wide?2:3):h.d===4?1:4;if(prev!==tool)add(p,8,'Tool change',tool);prev=tool;let e=[h.x,h.y,60];add(e,Math.hypot(e[0]-p[0],e[1]-p[1])/50,'Rapid XY',tool);e=[h.x,h.y,18];add(e,42/50,'Approach',tool);const endz=failure?0.5:-2;add([h.x,h.y,endz],(18-endz)/3,'Drill',tool,i);if(failure)break;add([h.x,h.y,60],62/50,'Retract',tool);}return out;}
    const sample0=compile(route0),sample1=compile(route1);const seconds0=sample0.at(-1).end,seconds1=sample1.at(-1).end;
    function chart(values,labels,suffix,max){return `<svg viewBox="0 0 310 110">${values.map((v,i)=>`<text x="0" y="${20+i*48}" fill="#adc0cb" font-size="11">${labels[i]}</text><rect x="95" y="${6+i*48}" width="${v/max*140}" height="23" rx="3" fill="${i?'#69d7b7':'#587080'}"/><text x="${101+v/max*140}" y="${22+i*48}" fill="#e0eced" font-size="11">${v.toFixed(1)}${suffix}</text>`).join('')}</svg>`;}
    $('.timechart').innerHTML=chart([seconds0,seconds1],['Mixed tools','Grouped tools'],' s',Math.max(seconds0,seconds1));
    const costs=[seconds0,seconds1].map(s=>s/3600*90+15/10);$('.costchart').innerHTML=chart(costs,['Mixed tools','Grouped tools'],' $',Math.max(...costs));
    const view=$('.view'),scene=new THREE.Scene();scene.background=new THREE.Color('#18232a');
    const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));view.prepend(renderer.domElement);
    const camera=new THREE.PerspectiveCamera(38,1,.1,2000);camera.up.set(0,0,1);camera.position.set(225,-260,210);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,32);controls.enableDamping=true;
    scene.add(new THREE.HemisphereLight(0xddefff,0x1b2025,2.3));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(80,-90,250);scene.add(light);
    const mat=(color,metalness=.2)=>new THREE.MeshStandardMaterial({color,metalness,roughness:.48});const body=mat('#384c58'),railMat=mat('#7d98a6',.7),plateMat=mat('#6bb3b9',.55),fixtureMat=mat('#5e7280'),holderMat=mat('#bfcdd3',.75),toolMat=mat('#89b4be',.8),red=mat('#ff695f');
    function box(w,d,h,x,y,z,m,parent=scene){const o=new THREE.Mesh(new THREE.BoxGeometry(w,d,h),m);o.position.set(x,y,z);parent.add(o);return o;}
    box(225,165,18,0,0,-37,body);box(185,12,9,0,-46,-23,railMat);box(185,12,9,0,46,-23,railMat);
    box(28,32,180,0,85,53,body);box(110,30,18,0,64,143,body);box(20,12,115,0,61,67,railMat);
    const table=new THREE.Group();scene.add(table);box(135,100,12,0,0,-18,body,table);for(let x=-50;x<=50;x+=25)box(2,98,1,x,0,-11.5,railMat,table);
    const stock=new THREE.Group();table.add(stock);const clamp=box(10,16,9,47,20,20.5,fixtureMat,table);box(10,16,9,-47,20,20.5,fixtureMat,table);box(8,70,10,-40,0,-5,body,table);box(8,70,10,40,0,-5,body,table);
    const pathGroup=new THREE.Group();table.add(pathGroup);const spindle=new THREE.Group();scene.add(spindle);
    function cylinder(radius,height,z,m){const o=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,height,28),m);o.rotation.x=Math.PI/2;o.position.z=z;spindle.add(o);return o;}
    const cutter=cylinder(3,20,10,toolMat),holder=cylinder(9,22,51,holderMat),shaft=cylinder(3,20,30,holderMat);box(36,32,25,0,0,79,body,spindle);
    function makeStock(done=[]){for(const child of [...stock.children]){child.geometry.dispose();stock.remove(child);}const shape=new THREE.Shape();shape.moveTo(-50,-35);shape.lineTo(50,-35);shape.lineTo(50,35);shape.lineTo(-50,35);shape.closePath();for(const idx of done){const h=holes[idx],p=new THREE.Path();p.absarc(h.x,h.y,h.d/2,0,Math.PI*2,true);shape.holes.push(p);}const geo=new THREE.ExtrudeGeometry(shape,{depth:16,bevelEnabled:false,curveSegments:24});stock.add(new THREE.Mesh(geo,plateMat));for(let i=0;i<holes.length;i++){if(done.includes(i))continue;const h=holes[i],ring=new THREE.Mesh(new THREE.RingGeometry(h.d/2,h.d/2+.35,28),mat('#e7ce84'));ring.position.set(h.x,h.y,16.1);stock.add(ring);}}
    makeStock();
    function drawPath(q){for(const c of [...pathGroup.children]){c.geometry.dispose();c.material.dispose();pathGroup.remove(c);}for(const e of q){if(e.kind==='Tool change')continue;const g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...e.from),new THREE.Vector3(...e.to)]);pathGroup.add(new THREE.Line(g,new THREE.LineBasicMaterial({color:e.kind==='Drill'?0x6fe3b5:0x708da8,transparent:true,opacity:.45})));}}
    function select(n){const available=$('.slim').checked;$('.timechart').innerHTML=available?chart([seconds0,seconds1],['Mixed tools','Grouped tools'],' s',Math.max(seconds0,seconds1)):'<p class="warn">No feasible example recipe with this tool library.</p>';$('.costchart').innerHTML=available?chart(costs,['Mixed tools','Grouped tools'],' $',Math.max(...costs)):'<p class="warn">Cost withheld until a valid recipe exists.</p>';stage=n;playing=false;elapsed=0;oldDone=-1;holes[4].x=n===4?28:30;const failed=n===2||((n===4||n===5)&&!$('.slim').checked);queue=failed?compile([4],true,true):compile(n===1?route0:route1);total=queue.at(-1).end;drawPath(queue);$('.rail').querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===n));const s=stages[n];$('.panel').innerHTML=`<div class="eyebrow">${s[0]}</div><h2>${failed&&n!==2?'No verified alternative in this demo':s[1]}</h2><p>${failed&&n!==2?"The required clearance cannot be achieved with the available assemblies in this illustrated setup.":s[2]}</p><div class="label">${s[3]}</div><div class="item">${failed&&n!==2?"Part + restricted tool library + supported fixture":s[4]}</div><div class="label">${s[5]}</div><div class="item">${failed&&n!==2?"No verified recipe; explain the missing capability":s[6]}</div><div class="label">What this step proves</div><div class="callout">${s[7]}</div>${n===3?'<div class="label">Proposed rule · not executed here</div><code>if supported_orientation<br>and holder_z_overlaps(clamp)<br>and footprint_overlaps(clamp):<br>    return violation(evidence)</code>':''}${failed&&n!==2?'<p class="warn">T3 is unavailable. The planner must report this constraint instead of inventing a tool.</p>':''}`;$('.play').textContent='Play machine';makeStock();}
    stages.forEach((s,i)=>{const b=document.createElement('button');b.textContent=s[0];b.onclick=()=>select(i);$('.rail').append(b);});
    $('.play').onclick=()=>{if(elapsed>=total)elapsed=0;playing=!playing;$('.play').textContent=playing?'Pause':'Play machine';};$('.reset').onclick=()=>select(stage);$('.slim').onchange=()=>select(stage);$('.scrub').oninput=e=>{elapsed=Number(e.target.value)/1000*total;playing=false;$('.play').textContent='Play machine';};
    function pose(){const ev=queue.find(e=>elapsed<=e.end)||queue.at(-1);const f=Math.max(0,Math.min(1,(elapsed-ev.start)/(ev.end-ev.start||1)));const p=ev.from.map((x,i)=>x+(ev.to[i]-x)*f);table.position.x=-p[0];table.position.y=-p[1];spindle.position.z=p[2];const wide=ev.tool===2;holder.scale.x=holder.scale.z=wide?16/9:1;holder.position.z=wide?35:51;shaft.position.z=wide?22:30;shaft.scale.y=wide?.2:1;const d=ev.tool===1?4:ev.tool===4?8:6;cutter.scale.x=cutter.scale.z=d/6;const fail=(stage===2||((stage===4||stage===5)&&!$('.slim').checked))&&elapsed>=total-.05;clamp.material=fail?red:fixtureMat;holder.material=fail?red:holderMat;const done=queue.filter(e=>e.kind==='Drill'&&e.end<=elapsed&&e.to[2]<0).map(e=>e.hole);if(done.length!==oldDone){makeStock(done);oldDone=done.length;}$('.axis').textContent=`X ${p[0].toFixed(1)}  Y ${p[1].toFixed(1)}  Z ${p[2].toFixed(1)} · T${ev.tool}`;$('.clock').textContent=`${elapsed.toFixed(1)} / ${total.toFixed(1)} s`;$('.scrub').value=elapsed/total*1000;if(fail){$('.play').textContent='Replay failure';$('.overlay').innerHTML='ILLUSTRATIVE FAILURE<br>Holder / clamp intersection';}else{$('.overlay').innerHTML=`ILLUSTRATIVE MOTION REPLAY · 8×<br>${ev.kind} · ${done.length}/6 holes shown complete`;}}
    const resize=new ResizeObserver(()=>{const w=view.clientWidth,h=view.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});resize.observe(view);
    function animate(ts){if(playing){elapsed=Math.min(total,elapsed+Math.min(.1,(ts-lastTs)/1000)*8);if(elapsed>=total){playing=false;$('.play').textContent='Replay';}}lastTs=ts;pose();controls.update();renderer.render(scene,camera);frameId=requestAnimationFrame(animate);}select(0);frameId=requestAnimationFrame(animate);
    return ()=>{cancelAnimationFrame(frameId);resize.disconnect();controls.dispose();scene.traverse(o=>{o.geometry?.dispose();});for(const m of [body,railMat,plateMat,fixtureMat,holderMat,toolMat,red])m.dispose();renderer.dispose();};
  }
};
